#! /usr/bin/env python

from __future__ import print_function
import rospy
from geometry_msgs.msg import PoseStamped, Twist
from std_msgs.msg import String

class ClosedLoopPickBaseController(object):
    """ Convert from cluster (from segmentation node) to images for varied purposes.
    """
    
    def __init__(self):
        self._obj_pose_sub = rospy.Subscriber('~input_pose', PoseStamped, self.obj_pose_cb)
        self._event_in_sub = rospy.Subscriber('~event_in', String, self.event_in_cb)
        self._cmd_vel_pub = rospy.Publisher('~cmd_vel', Twist, queue_size=1)
        self._target_position = None
        self.p_x = 0.2
        self.p_y = -1.0
        self.c_x = 0.02
        self.c_y = 50.0
        self.max_vel = 0.1
        self.min_vel = -0.1
        self._moving = False

    def obj_pose_cb(self, msg):
        obj_position = msg.pose.position
        if not (obj_position.x == obj_position.y == obj_position.z == 0.0):
            self._target_position = obj_position
        else:
            self._target_position = None
        rospy.loginfo(self._target_position)
        if self._moving and self._target_position is not None:
            vel_x = ((self._target_position.z * self.p_x) + self.c_x) / (1.0 + (abs(self._target_position.y) * self.c_y))
            vel_y = self._target_position.y * self.p_y
            print(vel_x, vel_y)
            vel_x = max(self.min_vel, min(vel_x, self.max_vel))
            vel_y = max(self.min_vel, min(vel_y, self.max_vel))
            print(vel_x, vel_y)
            self._cmd_vel_pub.publish(self._get_twist(x=vel_x, y=vel_y))
        else:
            self._publish_zero_vel()

    def event_in_cb(self, msg):
        self._moving = msg.data == "e_start"

    def _get_twist(self, x=0.0, y=0.0, theta=0.0):
        """Return twist ros message object.

        :x: float
        :y: float
        :theta: float
        :returns: geometry_msgs.msg.Twist

        """
        msg = Twist()
        msg.linear.x = x
        msg.linear.y = y
        msg.angular.z = theta
        return msg

    def _publish_zero_vel(self):
        rospy.loginfo("Zero vel")
        self._cmd_vel_pub.publish(self._get_twist())

if __name__ == '__main__':
    rospy.init_node('closed_loop_pick_base_controller')
    CLPBC = ClosedLoopPickBaseController()

    rospy.spin()
    print("Exiting...")
    CLPBC._publish_zero_vel()
